server:
  port: 8888

logging:
  path: logs
  file: mylog.log

spring:
  application:
    name: mytest
  datasource:
    driver-class-mame: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/zbb  
    username: root
    password: zbb2133778

mybatis:
  type-aliases-package: com.course.model
  mapper-locations:
    - mapper/*